version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
      target: develop
    image: "andy_backend"
    container_name: "andy_backend"
    volumes:
      - ../application:/sites/app/application
    ports:
      - "8000:8000"
