version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
      target: develop
    image: andy_backend
    command: uvicorn application.api:app --host 0.0.0.0 --port 8000 --reload
    container_name: andy_backend
    env_file:
      - ./env/dev.env
    volumes:
      - ../application:/sites/app/application
    ports:
      - "8000:8000"

  db:
    image: postgres:15.1
    container_name: andy_postgres
    env_file:
      - ./env/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "50000:5432"
    depends_on:
      backend:
        condition: service_started

#  jenkins:
#    image: jenkins/jenkins:jdk17
#    container_name: jenkins
#    volumes:
#      - jenkins_home:/var/jenkins_home
#      - ../application:/sites/app/application
#      - ../Jenkinsfile:/var/jenkins_home/Jenkinsfile
#    environment:
#      - JENKINS_OPTS="--prefix=/"
#    ports:
#      - "8080:8080"
#      - "50000:50000"
#    networks:
#      - jenkins-net
#    depends_on:
#      - backend
#
#  redis:
#    image: redis:6.2
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ../application:/sites/app/application
#    depends_on:
#      - backend
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
#    container_name: elasticsearch
#    environment:
#      - node.name=elasticsearch
#      - cluster.name=es-docker-cluster
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - xpack.security.audit.enabled:false
#    volumes:
#      - es-data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - elastic
#    depends_on:
#      - backend
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.12.0
#    container_name: kibana
#    environment:
#      - node.name=kib8
#      - cluster.name=es-docker-cluster
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    networks:
#      - elastic
#    depends_on:
#      - backend
#      - elasticsearch

#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.12.0
#    container_name: logstash
#    volumes:
#      - ../logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    environment:
#      - NODE_NAME=logstash
#      - xpack.monitoring.enabled=true
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
#    ports:
#      - "5044:5044"
#    networks:
#      - elastic
#    depends_on:
#      - backend
#      - elasticsearch
#      - kibana

  rabbitmq:
    image: rabbitmq:3.10.25-management
    container_name: andy_rabbitmq
    env_file:
      - ./env/dev.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.0-alpine
    depends_on:
      - backend
      - db
    container_name: andy_redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
      target: develop
    image: andy_celery_worker
    command: > 
      sh -c '/sites/app/infrastructure/bin/docker-entrypoint.sh rabbitmq 5672 -- celery -A application.celery_app worker --logfile=/sites/app/application/logs/celery.log --autoscale=8,1 -E -O fair -Q celery,tasks-queue --pidfile='
    depends_on:
      backend:
        condition: service_started
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    container_name: andy_celery_worker
    env_file:
      - ./env/dev.env
    volumes:
      - ../application:/sites/app/application

  celery_beat:
      build:
        context: ..
        dockerfile: infrastructure/Dockerfile
        target: develop
      image: andy_celery_beat
      command: > 
        sh -c '/sites/app/infrastructure/bin/docker-entrypoint.sh rabbitmq 5672 -- celery -A application.celery_app beat --logfile=/sites/app/application/logs/celery.log --pidfile='
      depends_on:
        backend:
          condition: service_started
        db:
          condition: service_started
        celery_worker:
          condition: service_started
        rabbitmq:
          condition: service_started
        redis:
          condition: service_started
      container_name: andy_celery_beat
      env_file:
        - ./env/dev.env
      volumes:
        - ../application:/sites/app/application


#networks:
#  jenkins-net:
#  elastic:
#    driver: bridge
#
volumes:
  postgres_data:
#  jenkins_home:
#  es-data:
#    driver: local
#  logstash_data:
  rabbitmq_data:
